name: "Lint and Test"
on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: .github/workflows/frontend-setup

      - name: Lint check frontend
        run: pnpm run lint-check

      - name: Test frontend
        run: pnpm run test