name: "Lint and Test"
on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/frontend-setup

      - name: Lint check frontend
        run: pnpm run lint-check

      - name: Test frontend
        run: pnpm run test