name: "Release"

on:
  workflow_run:
    workflows: ["Lint and Test"]
    types: [ completed ]
  branch:
    - main # This is redundant because the workflow_run event only triggers on the main branch

jobs:
  publish-tauri:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/frontend-setup

      - name: Lint check frontend
        run: pnpm run lint-check

      - name: Test frontend
        run: pnpm run test

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: noter-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Noter v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false